function createfigure(xdata1, ydata1, zdata1, zdata2)
%CREATEFIGURE(XDATA1, YDATA1, ZDATA1, ZDATA2)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata
%  ZDATA2:  surface zdata

%  Auto-generated by MATLAB on 29-Apr-2015 12:51:01

% Create figure
figure1 = figure('Color',[1 1 1]);
colormap('summer');

% Create axes
axes1 = axes('Parent',figure1);
view(axes1,[-31 22]);
hold(axes1,'on');

% Create zlabel
zlabel({'$u_{f}(x)$, $\tilde{u}_{f}(x)$'},'FontSize',20,...
    'Interpreter','latex');

% Create ylabel
ylabel({'$f$'},'FontSize',20,'Interpreter','latex');

% Create xlabel
xlabel({'$x$'},'FontSize',20,'Interpreter','latex');

% Create title
title({'Finite Element Solutions for the Example Problem'},'FontSize',24,...
    'Interpreter','latex');

% Create surf
surf(xdata1,ydata1,zdata1,'Parent',axes1,'LineWidth',0.1,'FaceColor','none');

% Create surf
surf(xdata1,ydata1,zdata2,'Parent',axes1,'LineStyle','none');

