C
      SUBROUTINE FRIC(LM,TAU,DDTDDG,DDTDDP,DSLIP,SED,SPD,
     1 DDTDDT,PNEWDT,STATEV,DGAM,TAULM,PRESS,DPRESS,DDPDDH,SLIP,
     2 KSTEP,KINC,TIME,DTIME,NOEL,CINAME,SLNAME,MSNAME,NPT,NODE,
     3 NPATCH,COORDS,RCOORD,DROT,TEMP,PREDEF,NFDIR,MCRD,NPRED,
     4 NSTATV,CHRLNGTH,PROPS,NPROPS)
C
      INCLUDE 'ABA_PARAM.INC'
C
      CHARACTER*80 CINAME,SLNAME,MSNAME
      DIMENSION TAU(NFDIR),DDTDDG(NFDIR,NFDIR),DDTDDP(NFDIR),
     1          DSLIP(NFDIR),DDTDDT(NFDIR,2),STATEV(*),
     2          DGAM(NFDIR),TAULM(NFDIR),SLIP(NFDIR),TIME(2),
     3          COORDS(MCRD),RCOORD(MCRD),DROT(2,2),TEMP(2),
     4          PREDEF(*),PROPS(NPROPS)
C
       IF (LM .EQ. 2) RETURN
C
C  SPEED OF ROTATION, RADIUS AND CIRCUMFERENTIAL SLIP INCREMENT
C
      HTIME=TIME(2)-0.5*DTIME
      OMEGA=78.54D0*MAX(1.0D0-HTIME/4.5D0,0.0D0)         
      R=COORDS(1)
      DSLIP(1)=OMEGA*DTIME*R
C
C  COEFFICIENT OF FRICTION 
C
      AMU=PROPS(1)
C
C  PLASTIC DISSIPATION
C
      SPD=AMU*PRESS*DSLIP(1)
      LM=0
      TAU(1)=0.
      DDTDDG(1,1)=0.
      DDTDDP(1)=0.
      DDTDDT(1,1)=0.
C
      RETURN
      END
